### ISSUE TITLE
Angular 10.1: Step not placed correctly, highlight too small

### ISSUE THREAD

**Issue by ksilz** [leifermendez/ngx-copilot#3]
Hi,

I'm using the library with Angular 10.1. Two issues:

- When I'm wrapping a heading/paragraph with a step, the step window is squished to the very right.
- The "spotlight" has just the default size and doesn't cover the described element.

Here's a short video of both issues:

![Copilot is off](https://user-images.githubusercontent.com/1061209/95075265-d387f400-0707-11eb-8df3-d1f119ab4074.gif)

Here's the first step:

```
<h5 [copilot-step]="1" [copilot-template]="step1" copilot>
  <fa-icon icon="syringe" size="lg"></fa-icon>&nbsp;
  <span jhiTranslate="clean.home.vets.title"></span>
</h5>
```

And here's the second:

```
<a [copilot-step]="2" [copilot-template]="step2" [routerLink]="navigationPathCustomer" class="btn bg-primary btn-white y-link-as-button card-link" copilot>
  <fa-icon icon="table" size="lg"></fa-icon>&nbsp;
  <span class="font-weight-bold" jhiTranslate="clean.home.customers.manage"></span>
</a>
```

What am I doing wrong?

**Comment by leifermendez** [comment]
Hi @ksilz thank you for using this repo. 
So you can check this fork https://stackblitz.com/edit/ngx-copilot-pzwhw6?file=src/app/app.component.html on Step (4)

__The "spotlight" has just the default size and doesn't cover the described element.__
You have two possible solutions
1. Try wrapper your h5 tag in a div tag
2. Add a attribute `[copilot-mode]="'horizontal'" `

----
__When I'm wrapping a heading/paragraph with a step, the step window is squished to the very right.__
You can applicate a custom CSS style. Every modal step have a class name with name step

**Comment by leifermendez** [comment]
Can you help, add documentation for this attribute

**Comment by ksilz** [comment]
@leifermendez Thank you for your quick reply! 

So `copilot-mode]="'horizontal'"` works for the spotlight!

As far as "step window is squished to the very right" is concerned, that's probably because it shows in a card at the very right edge. Can I position the step window below the element?

**Comment by leifermendez** [comment]
Yeah, you can every element. If you want a make a replicate issue on stackblitz

**Comment by ksilz** [comment]
What do I need to do to get the step window below the element?

**Comment by leifermendez** [comment]
I don't have a solution implemented. For now, I would recommend you to make use of css styles based on the element name.
I leave you the link

https://stackblitz.com/edit/ngx-copilot-pzwhw6?file=src/app/app.component.css

![image](https://user-images.githubusercontent.com/15802366/95084451-32f0fe80-071e-11eb-906f-803574a76950.png)

**Comment by ksilz** [comment]
I'm sorry for not being clear. I **know** how I can customize the CSS. I **don't** know what CSS instructions I have to use to make the step window show below the element it explains

In your example, the step window for step 5 is smushed on the right:

![Step 5](https://user-images.githubusercontent.com/1061209/95089185-beb55b80-071b-11eb-8952-f1b58420d4a4.gif)

In my Stackblitz, how do I need to change the `copilot-view-step-5` style in `app.component.css` so that the step window for step 5 shows **below** the picture?

[Stackblitz](https://stackblitz.com/edit/ngx-copilot-iyonnb?file=src/app/app.component.css)

**Comment by leifermendez** [comment]
Ok, you must add the CSS style in 'style.css' or apply `::ng-deep`  in your CSS component file

https://stackblitz.com/edit/ngx-copilot-wm7tvk?file=src/app/app.component.css

**Comment by leifermendez** [comment]
![image](https://user-images.githubusercontent.com/15802366/95091633-fbd31b00-0726-11eb-920f-82ae946fab78.png)

Remember if you try on a mobile device behavior change because in 'style.css' exist some class with media queries

**Comment by ksilz** [comment]
Thank you, that works wonderfully!

One last question: Your library sets the background color in the element that's being highlighted to `rgb(207, 206, 255)`:

<img width="354" alt="Highlight" src="https://user-images.githubusercontent.com/1061209/95095281-c3c9d900-0722-11eb-8c69-38832e8d4bba.png">

I'm currently overwriting this for each step with white because I don't want it to be there. Can I leave this either out globally altogether or change the color globally?

**Comment by leifermendez** [comment]
In your `style.css` add 
```css
:root{
	--zoneColor:rgba(114, 113, 160, 0.5) !important
}
```

or you can pass next attribute for every step ` [copilot-color]="'rgb(255 0 0 / 26%)'"` with the color preferer

**Comment by ksilz** [comment]
Neither of these two worked, but I'm fine for now. Thank you again for your help!
